config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/popup'=>'home#popup'
  get 'home/no_aside'=>'home#no_aside'
  get 'feed',:to=>'home#feed'

  resources :intro, :blogs, :gallery_categories, :galleries, :notices, :faq_categories,:faqs, :histories, :questions, :guest_books

  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :comments, only: [:create, :destroy]


  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :path_names => {:sign_up => 'new', :sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :blog_categories, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end

    resources :blogs do
      resources :blog_comments
    end

    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection
      resources :question_comments
    end

    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection
      end
    end
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  is_impressionable
  acts_as_taggable
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  belongs_to :gallery_category, :autosave => true, :counter_cache => true
  mount_uploader :photo, GalleryUploader
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::AdminController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    category_condition = {enable: true}

    @gallery_categories = GalleryCategory.where(category_condition)

    if params[:category].present?
      @gallery_category = GalleryCategory.find(params[:category])
    end

    condition = { }

    if @gallery_category.present?
      condition[:gallery_category_id] = @gallery_category.id
    end

    @gallery_count = Gallery.where(condition).count
    @galleries = Gallery.where(condition).page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new
    @gallery_categories=GalleryCategory.all
    @gallery_category_id=params[:gallery_category_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery_categories=GalleryCategory.all
    @gallery_category_id=@gallery.gallery_category.id
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to admin_gallery_url(@gallery), notice: @controller_name +t(:message_success_create)}
        format.json { render :json => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        format.html { redirect_to admin_galleries_url, notice: @controller_name +t(:message_success_update)}
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to admin_galleries_url }
      format.json { head :ok }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:id,:gallery_category_id,:title,:photo,:content).merge(user_id: current_admin.id)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)
    @controller_name = t('activerecord.models.gallery')
    @title = t('activerecord.models.gallery')
    @meta_description = t(:meta_description_gallery)
  end

  # GET /galleries
  # GET /galleries.json
  def index
    @gallery_categories = GalleryCategory.all

    if (params[:gallery_category_id])
      @gallery_category_id = params[:gallery_category_id].to_i
    else
      @gallery_category_id = @gallery_categories[0].id
    end

    @galleries = Gallery.where(:gallery_category_id => @gallery_category_id).order(:id => 'desc').page(params[:page]).per(30)

    if (params[:id])
      @gallery = Gallery.find(params[:id])
    else
      @gallery = @galleries[0]
    end

    if @gallery
      @title = @gallery.title
      @meta_description = @gallery.content
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery_categories = GalleryCategory.all
    @gallery_category_id = @gallery.gallery_category_id
    @galleries = Gallery.where(:gallery_category_id => @gallery_category_id).order(:id => 'desc').page(params[:page]).per(30)

    if @gallery
      @title = @gallery.title
      @meta_description = @gallery.content

      set_meta_tags canonical: gallery_url(@gallery)
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new
    @gallery_categories = GalleryCategory.all
    if (params[:gallery_category_id])
      @gallery_category_id = params[:gallery_category_id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery_categories = GalleryCategory.all
    @gallery_category_id = @gallery.gallery_category.id
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), :notice => @controller_name + t(:message_success_create) }
        format.json { render :json => @gallery, :status => :created, :location => @gallery }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update_attributes(gallery_params)
        format.html { redirect_to gallery_url(@gallery), :notice => @controller_name + t(:message_success_update) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gallery.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url(:gallery_category_id => @gallery.gallery_category_id) }
      format.json { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def gallery_params
    params.require(:gallery).permit(:id, :gallery_category_id, :title, :photo, :photo_cache, :content).merge(user_id: current_user.id)
  end
end

app/views/admin/galleries/_form.html.erb
<%= form_for [:admin, gallery],:html => {:multipart => true} do |f| %>
  <% if gallery.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this notice from being saved:</h2>
    <ul>
      <% gallery.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :gallery_category_id %>
    <%= f.select :gallery_category_id, options_from_collection_for_select(GalleryCategory.where(:enable=>true), 'id', 'title',@gallery_category_id),:class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title,:class=>'form-control',:required=>'required' %>
  </div>
  <div class="form-group">
    <%= f.label :photo %>
      <% if gallery.photo? %>
      <%= image_tag(gallery.photo.small_thumb) %>
      <% end %>
      <%= f.file_field :photo %>
      <%= f.hidden_field :photo_cache %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content,:class=>'form-control',:required=>'required' %>
  </div>
  <div class="form-group actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/admin/galleries/_nav.html.erb
<%
    a_class = 'nav-link'
    b_class = 'nav-link'

    if params[:controller] == 'admin/galleries'
      a_class += ' active'
    end

    if params[:controller] == 'admin/gallery_categories'
      b_class += ' active'
    end

  %>
  <div class="col-12">
    <nav class="sub-nav">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to t(:gallery, scope: [:activerecord, :models]), admin_galleries_path, { :class => a_class } %></li>
        <li class="nav-item"><%= link_to t(:gallery_category, scope: [:activerecord, :models]), admin_gallery_categories_path, { :class => b_class } %></li>
      </ul>
    </nav>
  </div>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>
<%= link_to t(:link_show), admin_gallery_path(@admin_gallery) %> |
<%= link_to t(:link_list), admin_galleries_path %>

app/views/admin/galleries/index.html.erb
<%
	a_class='nav-link'
	unless @gallery_category.present?
		a_class+=' active'
	end
%>
<div class="col-12">
	<nav class="sub-nav">
		<ul class="nav nav-pills">
			<li class="nav-item"><%= link_to t(:all), admin_galleries_path, class: a_class %></li>
			<% unless @gallery_categories.empty? %>
				<% @gallery_categories.each do |blog_category|
					b_class='nav-link'

					if @gallery_category.present?
						if @gallery_category.id==blog_category.id
							b_class+=' active'
						end
					end
				%>
					<li class="nav-item"><%=link_to blog_category.title,admin_galleries_path(:category=>blog_category),class: b_class %></li>
				<% end %>
			<% end %>
		</ul>
	</nav>
</div>
<div class="col-12">
	<h2 class="float-start hidden-title"><%= t(:gallery_list) %></h2>
	<div class="float-end">
		<p class="summary">
			<span id="list_count" style="display:none"><%=@gallery_count %></span>
			<%=raw t(:there_are_n_galleries,count: @gallery_count) %>
		</p>
	</div>
</div>
<article class="col-12">
	<table class="table table-striped table-hover">
		<colgroup>
			<col style="width:120px">
			<col>
			<col>
			<col>
			<col style="width:100px">
			<col style="width:210px">
			<% if can?(:update, Gallery) || can?(:delete, Gallery) %>
				<col <%=manage_width(Gallery) %>>
			<% end %>
		</colgroup>
		<thead class="thead-default">
		<tr>
			<th class="text-center"><%= t(:enable,scope:[:activerecord,:attributes,:gallery]) %></th>
			<th><%= t(:title,scope:[:activerecord,:attributes,:gallery]) %></th>
			<th><%= t(:gallery_category, scope: [:activerecord, :attributes, :gallery]) %></th>
			<th class="text-right"><%= t(:photo,scope:[:activerecord,:attributes,:gallery]) %></th>
			<th class="text-right"><%= t(:label_count) %></th>
			<th class="text-right"><%= t(:created_at,scope:[:activerecord,:attributes,:gallery]) %></th>
			<% if can?(:update, Gallery) || can?(:delete, Gallery) %>
				<th class="text-center"><%= t(:manage) %></th>
			<% end %>
		</tr>
		</thead>
		<tbody>
		<% unless @gallery_count.zero? %>
			<% @galleries.each_with_index do |gallery,index| %>
				<tr>
					<td>
						<div class="form-check form-switch">
							<input
								class="form-check-input"
								type="checkbox"
								id="notice_display<%= index %>"
								value="<%= gallery.id %>"
								<% if gallery.enable %> checked <% end %>
							>
							<label class="form-check-label" for="notice_display<%= index %>">
								<% if gallery.enable %> <%= t(:display) %> <% else %> <%= t(:hidden) %> <% end %>
							</label>
						</div>
					</td>
					<td><%= link_to gallery.title,admin_gallery_path(gallery) %></td>
					<td><%=gallery.gallery_category.title %></td>
					<td class="text-right">
						<% if gallery.photo.present? %>
							<%= image_tag gallery.photo.small_thumb.url %>
						<% else %>
							<%= t(:not_insert) %>
						<% end %>
					</td>
					<td class="text-right"><%= gallery.impressionist_count(:filter => :ip_address) %></td>
					<td class="text-right"><%= I18n.l gallery.created_at.to_date, :format => :long %></td>
					<% if can?(:update, gallery) or can?(:delete, gallery) %>
						<td class="text-right">
							<% if can? :update, gallery %>
								<%= link_to edit_admin_gallery_path(gallery), :class => "btn btn-secondary" do %>
									<%= t(:edit) %>
								<% end %>
							<% end %>
							<% if can? :delete, gallery %>
								<%= link_to admin_gallery_path(gallery), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
									<%= t(:delete) %>
								<% end %>
							<% end %>
						</td>
					<% end %>
				</tr>
			<% end %>
		<% else %>
			<tr>
				<td colspan="8" class="text-center"><%= t(:no_data) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
	<div class="pagination justify-content-center">
		<%= paginate @galleries %>
	</div>
	<%= link_to t(:add), new_admin_gallery_path, :class => "btn btn-primary" %>
</article>

app/views/admin/galleries/new.html.erb
<%= render 'form',:gallery=>@gallery %>
<%= link_to t(:link_list), admin_galleries_path %>

app/views/admin/galleries/show.html.erb
<div class="sl_show">
	<p>
		<b><%=t(:title,scope:[:activerecord,:attributes,:gallery]) %></b>
		<%= @gallery.title %>
	</p>
	<p>
		<b><%=t(:enable,scope:[:activerecord,:attributes,:gallery]) %></b>
		<%=raw flagToString(@gallery.enable) %>
	</p>
	<p>
  	<b><%=t(:label_created_at) %></b>
  	<%= @gallery.created_at %>
  </p>
  <p>
  	<b><%=t(:label_updated_at) %></b>
  	<%= @gallery.created_at %>
  </p>
</div>
<% if can? :update, @gallery %>
<%= link_to t(:link_edit), edit_admin_gallery_path(@gallery) %> |
<% end %>
<%= link_to t(:link_list), admin_galleries_path %>