config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/popup'=>'home#popup'
  get 'home/no_aside'=>'home#no_aside'
  get 'feed',:to=>'home#feed'

  resources :intro, :blogs, :gallery_categories, :galleries, :notices, :faq_categories,:faqs, :histories, :questions, :guest_books

  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :comments, only: [:create, :destroy]


  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :path_names => {:sign_up => 'new', :sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :blog_categories, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end

    resources :blogs do
      resources :blog_comments
    end

    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection
      resources :question_comments
    end

    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection
      end
    end
  end
end

app/models/admin.rb
class Admin < User
    default_scope { where(admin: true) }

    def self.model_name
        User.model_name
    end
end

app/models/answer.rb
class Answer < ApplicationRecord
  acts_as_votable

  belongs_to :question, counter_cache: true
  belongs_to :user, counter_cache: true
  validates_presence_of :content

  has_rich_text :content
end

app/models/blog.rb
class Blog < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content
  #ActsAsTaggableOn.delimiter = ','
  #ActsAsTaggableOn.force_lowercase = true
  validates_presence_of :title, :description
  validates_length_of :title, :minimum => 2, :maximum => 60
  belongs_to :user
  belongs_to :blog_category, :autosave => true, :counter_cache => true
  has_one :blog_picture, dependent: :destroy
  accepts_nested_attributes_for :blog_picture, :allow_destroy => true
end

app/models/blog_picture.rb
class BlogPicture < ApplicationRecord
  belongs_to :blog, autosave: true, counter_cache: true
  mount_uploader :picture, BlogPictureUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]
  acts_as_votable

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  is_impressionable
  has_rich_text :content

  validates_presence_of :title
  belongs_to :faq_category, :autosave=>true
end

app/models/faq_category.rb
class FaqCategory < ApplicationRecord
  validates_presence_of :title
  has_many :faq, :dependent=> :destroy
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  is_impressionable
  acts_as_taggable
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  belongs_to :gallery_category, :autosave => true, :counter_cache => true
  mount_uploader :photo, GalleryUploader
end

app/models/guest_book.rb
class GuestBook < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content

  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60
  belongs_to :user, optional: true
end

app/models/history.rb
class History < ActiveRecord::Base
  validates_presence_of :year, :title
  belongs_to :user,:autosave=>true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/intro.rb
class Intro < ApplicationRecord
  belongs_to :user, :autosave=>true  
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true  
  has_many :intro_photo, :foreign_key => :id, :dependent => :destroy
end

app/models/intro_photo.rb
class IntroPhoto < ApplicationRecord
  validates_presence_of :photo, :alt
  belongs_to :intro, :autosave=>true
  accepts_nested_attributes_for :intro, :allow_destroy => true
  mount_uploader :photo, IntroPhotoUploader
end

app/models/notice.rb
class Notice < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content

  validates_presence_of :title
  validates_length_of :title, minimum: 4, maximum: 60
  belongs_to :user, :autosave=>true
end

app/models/question.rb
class Question < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content

  validates_presence_of :title
  validates_length_of :title, minimum: 4, maximum: 60
  belongs_to :user

  has_many :answers, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  belongs_to :user, :autosave=>true
  has_many :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag, :counter_cache => true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatables
  validates_presence_of :nickname
  validates_uniqueness_of :email
  has_many :user_photo, :dependent=> :destroy
  has_many :notice, :dependent=> :destroy
  has_many :blog, :dependent=> :destroy
  has_many :gallery, :dependent=> :destroy

  has_one :user_picture, dependent: :destroy
  accepts_nested_attributes_for :user_picture, allow_destroy: true

  def remember_me
    super || false
  end

  def admin?
    admin
  end
end

app/models/user_ability.rb
class UserAbility
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin? # Admin user
      can :manage, :all
    else # Non-admin user
      can :manage, [Question,GuestBook]
    end
  end
end

app/models/user_picture.rb
class UserPicture < ApplicationRecord
  belongs_to :user, autosave: true, counter_cache: true
  mount_uploader :picture, UserPictureUploader
end

app/views/layouts/admin/_aside.html.erb
<aside id="main-menu" class="col-12 col-md-3 col-lg-2 col-xl-1">
  <h1 class="col-12"><%= link_to t(:service_name), admin_root_path %></h1>
  <nav>
    <ul class="nav">
      <li class="nav-item
            <% if ['admin/blogs','admin/blog_categories'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_blogs_path, :class => "nav-link" do %>
          <i class="material-icons">payment</i><span><%= t(:blog, scope: [:activerecord,:models]) %></span>
        <% end %>
      </li>

      <li class="nav-item
            <% if ['admin/galleries','admin/gallery_categories'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_galleries_path, :class => "nav-link" do %>
          <i class="material-icons">payment</i><span><%= t(:gallery, scope: [:activerecord,:models]) %></span>
        <% end %>
      </li>
      <li class="nav-item
            <% if ['admin/questions'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_questions_path, :class => "nav-link" do %>
          <i class="material-icons">payment</i><span><%= t(:question, scope: [:activerecord,:models]) %></span>
        <% end %>
      </li>
      <li class="nav-item
            <% if ['admin/guest_books'].include?(params[:controller]) %> active
            <% end %>">
        <%= link_to admin_guest_books_path, :class => "nav-link" do %>
          <i class="material-icons">settings</i><span><%= t(:guest_book, scope: [:activerecord,:models]) %></span>
        <% end %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/admin/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <address class="col-12">
        <a href="<%=t(:site_full_url) %>" target="_blank"><%=t(:application_name) %></a>
        &nbsp;&nbsp; 관리자 페이지
      </address>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="row">
  <div class="col-12">
    <% if ['admin/blogs','admin/blog_categories'].include?(params[:controller]) %>
      <%= render 'admin/blogs/nav' %>
    <% end %>
    <% if ['admin/galleries','admin/gallery_categories'].include?(params[:controller]) %>
      <%= render 'admin/galleries/nav' %>
    <% end %>
    <ul id="top-menu">
      <% if admin_signed_in? %>
        <li id="admin-info">
          <% if current_admin.user_picture.present? %>
            <%= image_tag(current_admin.user_picture.picture.small_thumb.url, { :height => 50, :width => 50 }) %>
          <% end %>
          <span class="text-dark"><%= current_admin.nickname %></span>
        </li>
        <li>
          <%= link_to destroy_admin_session_path, :id => "p_logout", :method => :delete do %>
            <i class="material-icons" style="font-size:35px;vertical-align:middle">highlight_off</i><span><%= t(:logout) %></span>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_admin_session_path do %>
            <i class="material-icons">login</i><span><%= t(:login) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/admin/_login_footer.html.erb
<%
  l_class='dropdown-item d-flex align-items-center'

  ko_class=l_class+' ko'
  en_class=l_class+' en'
  zh_cn_class=l_class+' zh-CN'

  case session[:locale].to_s
  when 'en'
    en_class+=' active'
  when 'zh-CN'
    zh_cn_class+=' active'
  else
    ko_class+=' active'
  end

  puts session[:locale]
%>
<footer>
  <div class="container">
    <ul class="row justify-content-center">
      <li class="col-6 text-center text-xl-start">
        <address class="col-12 text-center">
          <a href="https://www.jedaeroweb.co.kr" target="_blank"><%=t(:jedearoweb) %></a>
          &nbsp;&nbsp; CopyLeft. 2020, jedaeroweb. All wrongs reserved.
        </address>
      </li>
      <!--  <li class="col-6 col-lg-4 dropdown">
        <%= link_to '#', { class: 'dropdown-toggle',role:"button",'data-bs-toggle': "dropdown",'aria-expanded':"false"} do %>
          <%=t(:language) %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <%=link_to '🇰🇷 한국어', url_for(:locale => 'ko'),:class=>ko_class,:'aria-pressed'=>"true" %>
          </li>
          <li>
            <%=link_to '🇺🇸 english', url_for( :locale => 'en'),:class=>en_class,:'aria-pressed'=>"false" %>
          </li>
          <li>
            <%=link_to '🇨🇳 汉语', url_for( :locale => 'zh-CN'),:class=>zh_cn_class,:'aria-pressed'=>"false" %>
          </li>
        </ul>
      </li> -->
      <li class="col-6 text-center text-xl-start">
        <%= link_to '#', { class: 'dropdown-toggle d-flex align-items-center gap-2',
                           role: "button",
                           'data-bs-toggle': "dropdown",
                           'aria-expanded': "false" } do %>
          <span><%=t(:theme) %></span>
          <span class="current-theme-icon"></span>
        <% end %>
        <ul class="dropdown-menu">
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="light">
              <span class="icon">☀️</span>
              <%=t(:light) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="dark">
              <span class="icon">🌙</span>
              <%=t(:dark) %>
            </button>
          </li>
          <li>
            <button class="dropdown-item d-flex align-items-center gap-2" data-bs-theme-value="auto">
              <span class="icon">🌓</span>
              <%=t(:auto) %>
            </button>
          </li>
        </ul>
      </li>

    </ul>
  </div>
</footer>

app/views/layouts/admin/_login_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1><%= link_to root_path do %>
            <span class="logo"><%= t(:service_name) %></span>
          <% end %>
        </h1>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%= t(:service_name) %></title>
  <meta name="description" content="<%= t(:service_name) %>">
  <meta name="author" content="Sleeping-Lion">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
  <%= stylesheet_link_tag "admin", :media => "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "actiontext", :media => "all", "data-turbolinks-track" => true %>
  <link rel="icon" href="/favicon.ico">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <%= render :partial => 'layouts/admin/aside' %>
    <div class="col-12 col-md-9 col-lg-10 col-xl-11">
      <%= render :partial => 'layouts/admin/header' %>
      <div id="mom" class="row">
        <div id="main" class="col-12">
          <div class="sub-main p-3 p-lg-4 p-xl-5">
            <%= render :partial => 'layouts/notice', :locals => { :notice => notice, :alert => alert } %>
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render :partial => 'layouts/admin/footer' %>
    </div>
  </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
<%= javascript_importmap_tags %>
</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale %>">
<head>
  <meta charset="utf-8">
  <title><%=t(:service_name)%></title>
  <meta name="description" content="<%=t(:service_name)%>">
  <meta name="author" content="Sleeping-Lion">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag "admin", :media => "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "actiontext", :media => "all", "data-turbolinks-track" => true %>
  <link rel="icon" href="/favicon.ico">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
<%= render :partial => 'layouts/admin/login_header' %>
<div id="mom">
  <main id="main" class="container">
    <div class="sub-main p-5">
      <%= render :partial => 'layouts/notice', :locals => { :notice => notice, :alert => alert } %>
      <%= yield %>
    </div>
  </main>
</div>
<%= render :partial => 'layouts/admin/login_footer' %>
<%= javascript_importmap_tags %>
</body>
</html>

app/views/layouts/admin/popup.html.erb
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <%= yield %>
  </div>
</div>

app/views/site/index.html.erb
<section id="section_site_intro" class="sub_main">
	<%= render :partial => 'layouts/ad' %>
	<article>
		<h3>사이트 소개</h3>
		<p>수정이의 미모와 애교를 널리 알리려는 목적으로 <%=link_to '잠자는-사자','http://www.sleepinglion.pe.kr' %>가 제작한 사이트입니다.</p>
	</article>
	<article>
		<h3>본 사이트는 소수 사용자의 사용성 향상을 위해 노력합니다.</h3>
		<ol>
			<li>IE가 아닌 환경에서도 사용 가능한 사이트</li>
			<li>자바스크립트 없이도 사용 가능한 사이트</li>
			<li>CSS 없이도 사용 가능한 사이트</li>
			<li>저 해상도에서도 사용 가능한 사이트</li>
			<li>이미지 없이도 사용 가능한 사이트</li>
			<li>저 컬러에서도 같은 색상으로 표현 되는 사이트</li>
			<li>저용량으로 빠르게 반응하는 사이트</li>
		</ol>
	</article>
	<article>
		<figure>
			<%=image_tag 'rails.png' %>
			<figcaption>rails</figcaption>			
		</figure>
	</article>
</section>