config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/popup'=>'home#popup'
  get 'home/no_aside'=>'home#no_aside'
  get 'feed',:to=>'home#feed'

  resources :intro, :blogs, :gallery_categories, :galleries, :notices, :faq_categories,:faqs, :histories, :questions, :guest_books

  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :comments, only: [:create, :destroy]


  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :path_names => {:sign_up => 'new', :sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :blog_categories, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end

    resources :blogs do
      resources :blog_comments
    end

    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection
      resources :question_comments
    end

    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection
      end
    end
  end
end

app/models/history.rb
class History < ActiveRecord::Base
  validates_presence_of :year, :title
  belongs_to :user,:autosave=>true
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.history')
  end

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.order(@menu_setting.order).page(params[:page]).per(@menu_setting.per)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/new
  # GET /histories/new.json
  def new
    @history = History.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to histories_path, :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @history, status: :created, location: @history }
      else
        format.html { render action: "new" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update_attributes(history_params)
        format.html { redirect_to histories_path, :notice=> @controller_name +t(:message_success_update)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_path }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_history
    @history = Histro.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def history_params
    params.require(:history).permit(:year, :title, :content)
  end
end

app/views/histories/_form.html.erb
<%= form_for @history do |f| %>
	<% if @history.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>
		<ul>
			<% @history.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-group">
		<%= f.label :year %><br />
		<%= f.text_field :year, :class=>'form-control', :required=>'required' %>
	</div>	
	<div class="form-group">
		<%= f.label :title %><br />
		<%= f.text_field :title, :class=>'form-control', :required=>'required' %>
	</div>
	<div class="form-group">
		<%= f.label :content %><br />
		<%= f.text_area :content, :class=>'form-control', :required=>'required', :id => "sl_content" %>
	</div>
	<div class="form-group actions">
		<%= f.submit :class=>"btn btn-primary" %>
	</div>
<% end %>

app/views/histories/edit.html.erb
<section id="sl_history_edit">
	<%= render 'form' %>
	<%= link_to t(:link_show), @history %> |
	<%= link_to t(:link_list), histories_path %>
</section>

app/views/histories/index.html.erb
<article id="sl_history_index">
		<h2>약력</h2>
		<dl>
			<% unless @histories.empty? %>
			<% @histories.each do |history| %>			
			<dt><%=history.year %></dt>
			<dd>
				<b><%=history.title %></b>
				<%=simple_format(history.content) %>
			<% if user_signed_in? %>
			<% if current_user.admin? %>				
				<div class="history_menu">
					<%= link_to t(:link_edit), edit_history_path(history) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), history, method: :delete, data: { confirm: t(:delete_confirm) } %>
				</div>
			<% end %>
			<% end %>				
			</dd>
			<% end %>
			<% end %>
		</dl>
	<% if user_signed_in? %>
	<% if current_user.admin? %>			
		<%= link_to t(:link_new), new_history_path %>
	<% end %>
	<% end %>		
</article>

app/views/histories/new.html.erb
<section id="sl_history_new">
	<%= render 'form' %>
	<%= link_to t(:link_list), histories_path %>
</section>

app/views/histories/show.html.erb
<section id="sl_history_show">
	<div class="slboard_content">
		<div class="sl_content_header">
			<h3><%= @notice.title %></h3>
			<p><%=t(:label_name) %> :<%= @notice.user.name %>&nbsp;&nbsp;&nbsp; <%=t(:label_creatd_at) %> : <%= @notice.created_at %></p>
		</div>
		<div class="sl_content_main">
			<div class="sl_content_text"><%= simple_format(@notice.notice_content.content) %></div>
		</div>
	</div>
	<div id="sl_content_bottom_menu">
		<%= link_to t(:link_list),notices_path %>
		<% if user_signed_in? %>
		<% if current_user.admin? %>
		&nbsp; | &nbsp; <%= link_to t(:link_edit), edit_notice_path(@notice) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), @notice, method: :delete, data: { confirm: t(:delete_confirm)} %>
		<% end %>
		<% end %>
	</div>
</section>