config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/popup'=>'home#popup'
  get 'home/no_aside'=>'home#no_aside'
  get 'feed',:to=>'home#feed'

  resources :intro, :blogs, :gallery_categories, :galleries, :notices, :faq_categories,:faqs, :histories, :questions, :guest_books

  get 'tags/:tag', to: 'tags#index', as: :tag
  resources :comments, only: [:create, :destroy]


  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :path_names => {:sign_up => 'new', :sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :intro,:gallery_categories, :galleries, :faq_categories,:faqs, :blog_categories, :notices, :site, :intro, :contacts, :notices, :histories, :portfolios
    resources :questions do
      resources :question_comments
    end

    resources :blogs do
      resources :blog_comments
    end

    resources :questions do
      get 'password',:on=>:collection
      post 'password',:on=>:collection
      resources :question_comments
    end

    resources :guest_books do
      resources :guest_book_comments do
        get 'password',:on=>:collection
        post 'password',:on=>:collection
      end
    end
  end
end

app/models/notice.rb
class Notice < ApplicationRecord
  is_impressionable
  acts_as_taggable
  acts_as_commentable
  acts_as_votable
  has_rich_text :content

  validates_presence_of :title
  validates_length_of :title, minimum: 4, maximum: 60
  belongs_to :user, :autosave=>true
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < Admin::AdminController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @notices = Notice.order('id desc').page(params[:page]).per(params[:per_page])
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    @notice.build_notice_content
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @admin_notice = Notice.new(notice_params)

    respond_to do |format|
      if @admin_notice.save
        format.html { redirect_to admin_notice_path(@admin_notice), notice: @controller_name +t(:message_success_create)}
        format.json { render action: 'show', status: :created, location: @admin_notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @admin_notice.update(notice_params)
        format.html { redirect_to admin_notice_path(@admin_notice), notice: @controller_name +t(:message_success_update)}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @admin_notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @admin_notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:id,:title,:count,notice_content_attributes: [:id,:content]).merge(user_id: current_admin.id)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)
    @controller_name=t('activerecord.models.notice')
  end

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.order(:id=>'desc').page(params[:page]).per(15)
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
    @notice.build_notice_content

    @script="board/new"
  end

  # GET /notices/1/edit
  def edit
    @script="board/edit"
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.user_id=current_user.id

    @script="board/new"

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: @controller_name +t(:message_success_create)}
        format.json { render action: 'show', status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    @script="board/edit"

    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: @controller_name +t(:message_success_update)}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:id,:title,notice_content_attributes: [:id,:content])
  end
end

app/views/admin/notices/_form.html.erb
<%= form_for [:admin,notice] do |f| %>
  <% if notice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>
    <ul>
      <% notice.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class=>'form-control', :required=>'required' %>
  </div>
  <%= f.fields_for :notice_content do |c| %>
  <div class="form-group">
    <%= c.label :content %>
    <%= c.text_area :content, :class=>'form-control', :id => "sl_content" %>
  </div>
  <% end %>
  <div class="form-group">
  	<%= f.label :count %>
  	<%= f.number_field :count %>
  </div>  
  <div class="form-group">
  	<%= f.label :enable %>
  	<%= f.check_box :enable %>
  </div>
  <div class="form-group actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/admin/notices/_nav.html.erb
<%
    a_class = 'nav-link'
    b_class = 'nav-link'

    if params[:controller] == 'admin/blogs'
      a_class += ' active'
    end

    if params[:controller] == 'admin/blog_categories'
      b_class += ' active'
    end

  %>
  <div class="col-12">
    <nav class="sub-nav">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to t(:blog, scope: [:activerecord, :models]), admin_blogs_path, { :class => a_class } %></li>
        <li class="nav-item"><%= link_to t(:blog_category, scope: [:activerecord, :models]), admin_blog_categories_path, { :class => b_class } %></li>
      </ul>
    </nav>
  </div>

app/views/admin/notices/edit.html.erb
<%= render 'form',:notice=>@admin_notice %>
<%= link_to t(:link_show), admin_notice_path(@admin_notice) %> |
<%= link_to t(:link_list), admin_notices_path %>

app/views/admin/notices/index.html.erb
<%
	a_class='nav-link'
	unless @blog_category.present?
		a_class+=' active'
	end
%>
<div class="col-12">
	<nav class="sub-nav">
		<ul class="nav nav-pills">
			<li class="nav-item"><%= link_to t(:all), admin_blogs_path, class: a_class %></li>
			<% unless @blog_categories.empty? %>
				<% @blog_categories.each do |blog_category|
					b_class='nav-link'

					if @blog_category.present?
						if @blog_category.id==blog_category.id
							b_class+=' active'
						end
					end
				%>
					<li class="nav-item"><%=link_to blog_category.title,admin_blogs_path(:category=>blog_category),class: b_class %></li>
				<% end %>
			<% end %>
		</ul>
	</nav>
</div>
<div class="col-12">
	<h2 class="float-start hidden-title"><%= t(:blog_list) %></h2>
	<div class="float-end">
		<p class="summary">
			<span id="list_count" style="display:none"><%=@blog_count %></span>
			<%=raw t(:there_are_n_blogs,count: @blog_count) %>
		</p>
	</div>
</div>
<article class="col-12">
	<table class="table table-striped table-hover">
		<colgroup>
			<col style="width:120px">
			<col>
			<col>
			<col>
			<col style="width:100px">
			<col style="width:210px">
			<% if can?(:update, Blog) || can?(:delete, Blog) %>
				<col <%=manage_width(Blog) %>>
			<% end %>
		</colgroup>
		<thead class="thead-default">
		<tr>
			<th class="text-center"><%= t(:enable,scope:[:activerecord,:attributes,:blog]) %></th>
			<th><%= t(:title,scope:[:activerecord,:attributes,:blog]) %></th>
			<th><%= t(:blog_category_id, scope: [:activerecord, :attributes, :blog]) %></th>
			<th class="text-right"><%= t(:picture,scope:[:activerecord,:attributes,:blog_picture]) %></th>
			<th class="text-right"><%= t(:label_count) %></th>
			<th class="text-right"><%= t(:created_at,scope:[:activerecord,:attributes,:blog]) %></th>
			<% if can?(:update, Blog) || can?(:delete, Blog) %>
				<th class="text-center"><%= t(:manage) %></th>
			<% end %>
		</tr>
		</thead>
		<tbody>
		<% unless @blog_count.zero? %>
			<% @blogs.each_with_index do |blog,index| %>
				<tr>
					<td>
						<div class="custom-control custom-switch">
							<input type="checkbox" class="custom-control-input" id="notice_display<%=index %>" value="<%=blog.id %>" <% if blog.enable %> checked<% end %>>
							<label class="custom-control-label" for="notice_display<%=index %>"><% if blog.enable %> <%=t(:display) %><% else %><%=t(:hidden) %><% end %> </label>
						</div>
					</td>
					<td><%= link_to blog.title,admin_blog_path(blog) %></td>
					<td><%=blog.blog_category.title %></td>
					<td class="text-right">
						<% if blog.blog_picture.present? %>
							<%= image_tag blog.blog_picture.picture.small_thumb.url %>
						<% else %>
							<%= t(:not_insert) %>
						<% end %>
					</td>
					<td class="text-right"><%= blog.impressionist_count(:filter => :ip_address) %></td>
					<td class="text-right"><%= I18n.l blog.created_at.to_date, :format => :long %></td>
					<% if can?(:update, blog) or can?(:delete, blog) %>
						<td class="text-right">
							<% if can? :update, blog %>
								<%= link_to edit_admin_blog_path(blog), :class => "btn btn-secondary" do %>
									<%= t(:edit) %>
								<% end %>
							<% end %>
							<% if can? :delete, blog %>
								<%= link_to admin_blog_path(blog), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
									<%= t(:delete) %>
								<% end %>
							<% end %>
						</td>
					<% end %>
				</tr>
			<% end %>
		<% else %>
			<tr>
				<td colspan="8" class="text-center"><%= t(:no_data) %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
	<div class="pagination justify-content-center">
		<%= paginate @blogs %>
	</div>
	<%= link_to t(:add), new_admin_blog_path, :class => "btn btn-primary" %>
</article>

app/views/admin/notices/new.html.erb
<%= render 'form',:notice=>@admin_notice %>
<%= link_to t(:link_list), admin_notices_path %>

app/views/admin/notices/show.html.erb
<div class="sl_show">
	<p>
		<b><%=t(:title,scope:[:activerecord,:attributes,:notice]) %></b>
		<%= @admin_notice.title %>
	</p>
	<p>
  	<b><%=t(:content,scope:[:activerecord,:attributes,:notice_content]) %></b>
		<%= simple_format(@admin_notice.notice_content.content) %>
	</p>
	<p>
  	<b><%=t(:label_count) %></b>
  	<%=@admin_notice.count+@admin_notice.impressionist_count(:filter=>:ip_address) %>
  </p>
	<p>
		<b><%=t(:enable,scope:[:activerecord,:attributes,:notice]) %></b>
		<%=raw flagToString(@admin_notice.enable) %>
	</p>
	<p>
  	<b><%=t(:label_created_at) %></b>
  	<%= @admin_notice.created_at %>
  </p>
  <p>
  	<b><%=t(:label_updated_at) %></b>
  	<%= @admin_notice.created_at %>
  </p>
</div>
<% if can? :update, @admin_notice %>
<%= link_to t(:link_edit), edit_admin_notice_path(@admin_notice) %> |
<% end %>
<%= link_to t(:link_list), admin_notices_path %>